name: NTNC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13139
title: New Thought Northern Colorado
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#64557e'
    - '#fffdff'
    - '#b4afa9'
    - '#d5813a'
  brandStrength: 0.5723253581672907
  lightness: 0.02084410423412919
  saturation: 0.032962929690256715
  rhythmicContrast: 0.265346274478361
purpose: []
